# Generated by Django 3.1.2 on 2021-03-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('image', models.URLField(max_length=1000)),
                ('price', models.IntegerField()),
                ('release', models.DateField(auto_now_add=True)),
                ('lte_exists', models.BooleanField()),
            ],
        ),
    ]
